/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#9d3b62",
        "surface-container-high": "#eae7e7",
        "inverse-surface": "#313030",
        "tertiary-container": "#434340",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e5e2de",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#735c00",
        "outline": "#877277",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f2",
        "outline-variant": "#dac0c6",
        "secondary-container": "#fed65b",
        "on-tertiary-fixed-variant": "#474744",
        "on-surface": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#e5e2e1",
        "surface": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-container": "#f0eded",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffe088",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-tertiary-fixed": "#1c1c1a",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#7f234a",
        "on-surface-variant": "#544247",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-tertiary-container": "#b1afac",
        "primary-container": "#7a1f46",
        "error": "#ba1a1a",
        "tertiary": "#2d2d2a",
        "secondary-fixed-dim": "#e9c349",
        "surface-bright": "#fcf9f8",
        "background": "#fcf9f8",
        "primary-fixed": "#ffd9e2",
        "on-primary-fixed": "#3e001e",
        "surface-variant": "#e5e2e1",
        "inverse-primary": "#ffb0c8",
        "primary-fixed-dim": "#ffb0c8",
        "on-primary-container": "#ff8bb3",
        "on-secondary-fixed": "#241a00",
        "primary": "#5c0430"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-md": "16px",
        "gutter": "24px",
        "unit": "8px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "section-gap": "80px",
        "margin-desktop": "64px",
        "container-max": "1200px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
